### ISSUE TITLE
More data splits of VOC

### ISSUE THREAD

**Issue by charlesCXK** [ZHKKKe/PixelSSL#1]
Dear author:
Thank you for sharing! Could you share more data splits of your ECCV paper, such as data split of 1/16, 1/4, 1/2 of VOC? We want to run experiments based on more splits and make a comparison with the numbers reported in the paper. Thank you!

**Comment by ZHKKKe** [comment]
Thanks for your attention!

I have uploaded the PascalVOC data splits used in our paper to the **master** branch. You can try them now. Please create new scripts under the folder `pixelssl/task/sseg/script` and set new `sublabeled_path` in the scripts to retrain models (**4 GPUs** are required for each training). 

The script `pixelssl/task/sseg/dataset/PascalVOC/tool/random_sublabeled_samples.py` is used to create all PascalVOC data splits used in our paper. Actually, you can randomly generate new data splits for experiments. Note that different data splits may cause a large performance gap, especially when the amount of labeled data is small. For example, the mIOU gap of **SupOnly** could be **1.5%** under different **1/16** labeled data. Therefore, for each setup, the average over multiple runs (use different data splits) is reported in our paper.

If you have any problems in the experiment, please feel free to contact me.

BTW, It's my pleasure if you could contribute your implementation of the experiments on Cityscape to PixelSSL after you finish your work. The contributing document and the API document are coming soon.   :)

**Comment by charlesCXK** [comment]
Thank you!
