### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Rainfor1** [ZHKKKe/PixelSSL#4]
Hi ZHKKKE,

First of all, thank you for your work. Currently, I retrain the gct by PSPNet with the ResNet-101 backbone in Pascal VOC, and use the parameter of im_size=513, batch_size=4 with 4 gpus. However,  i am getting the error of insufficient memory. I retrained other methods you offered by using the parameter of im_size=513, batch_size=4 with 4 gpus and can get the accuracy provided by README.md. 

I want to know how you train the gct with 4 GPUs? Save memory by changing im_size=513 to im_size=321？Or is there any other way？

Thank you and regards

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

Which GPU are you using? For PSPNet, if you use 4 GPUs for training, the GCT algorithm requires about 12G memory (each GPU). I have tried to optimize the algorithm, but it still requires a lot of memory during training.
If you change the im_size to 321, the performance may be decreased.

Is it possible for you to use **8 GPUs** for training? If so, in the script `pspnet_pascalvoc_1-8_sslgct.py`, you can change:
```
('lr', 0.00025),
('batch_size', 4),
('unlabeled_batch_size', 2), 
```
to 
```
('lr', 0.000125),
('batch_size', 2),
('unlabeled_batch_size', 1), 
```

You can also use the results reported by us. For `PSPNet + GCT` under 1/2 label, the SSL performance is **73.92**. This results will be uploaded soon.

**Comment by Rainfor1** [comment]
Thank you very much for your answer.

I used 4 GPUs (each 12G). During the gct experiment, I found that the main GPU used for integration would exceed 12G memory. Next, i will try to solve the imbalance problem of memory by using `DistributedDataParallel`.

**Comment by ZHKKKe** [comment]
Yes. If you use `DistributedDataParallel`, the memory will be balanced better. I am sorry that I do not have time to implement it recently.

**Comment by Rainfor1** [comment]
Thank you again.
