### ISSUE TITLE
Add implementation for Semi-supervised Semantic Segmentation via Strong-weak Dual-branch Network

### ISSUE THREAD

**Issue by syorami** [ZHKKKe/PixelSSL#5]
Thanks for your sharing and the repo is quite helpful for me to understand the work in SSL segmentation. If possible, could you add the implementation of Semi-supervised Semantic Segmentation via Strong-weak Dual-branch Network (ECCV 2020), which is a simply dual branch network. It's a quite easy and inituitive idea but I could not reproduce the results with deeplabv2. It would be great if you could add this into the repo.

**Comment by ZHKKKe** [comment]
Hi, thanks for your attention.

I will check it and response you ASAP.

**Comment by ZHKKKe** [comment]
@syorami 
I have checked the paper. The paper seems focus more on weak-supervised learning. 
I am sorry that we do not have enough time to reproduce it this month.

**Comment by syorami** [comment]
Does 'weak-supervised learning' indicate the usage of DSRG to generate weak annotations?

**Comment by ZHKKKe** [comment]
Oh... Yep...
They use DSRG to generate weak annotations.. So we can regard the method as a semi-supervised method.
Now we are reproducing S4GAN. We will consider reproducing this work then.

**Comment by syorami** [comment]
Got it. Thanks for your kindly response.
